//! # fibonacci-dsp
//!
//! Allocation-free FM drone engine whose patch structure is generated by the
//! Fibonacci recursion `F(n) = F(n-1) + F(n-2)`.
//!
//! Every mathematical model used by the engine is documented in the workspace
//! `README.md`; the short version:
//!
//! - **Structure**: an algorithm is a Fibonacci recursion tree over 5 sine
//!   operators. Each of the 4 combination nodes is either `Series` (the larger
//!   sub-cluster phase-modulates the smaller one's carrier) or `Parallel`
//!   (both are carriers, summed). See [`algorithm`].
//! - **Ratios**: three operator frequency-ratio models — harmonic integers,
//!   Fibonacci numbers, and golden-ratio powers. See [`patch::RatioMode`].
//! - **Levels**: default modulator levels decay as `1/phi^(depth-1)`.
//! - **Drone voice**: no envelopes. Operators have power switches that are
//!   true resets (phase and feedback state zeroed), not bypasses. See
//!   [`voice::Voice`].
//!
//! The audio path ([`Voice::render`](voice::Voice::render)) performs no heap
//! allocation; algorithm compilation ([`algorithm::compile`]) happens at
//! patch-change time only.

pub mod algorithm;
pub mod melody;
pub mod patch;
mod phase;
pub mod reverb;
pub mod voice;

pub use algorithm::{compile, AlgorithmId, Combine, Compiled, ALGORITHMS, NUM_NODES, NUM_OPS};
pub use melody::{
    HoldSource, Melody, MelodyParams, Quantization, Scale, Tuning, NUM_SCALES, NUM_TUNINGS,
};
pub use patch::{index_response, master_gain, midi_to_hz, OpParams, Patch, RatioMode, PHI, PLASTIC};
pub use reverb::{StereoVerb, VerbParams};
pub use voice::{Frame, Voice};
